### ISSUE TITLE
Plan B SDP not supported anymore

### ISSUE THREAD

**Issue by guillaumepotier** [opentok/opentok-network-test-js#204]
This test is not working anymore for me since a few days, following Chrome dropping WebRTC Plan B. Could you possibly update the opentok dependency to have it working agin?

Best

**Comment by jeffswartz** [comment]
Hi, Guillaume. I cannot reproduce this issue. The app using the opentok-network-test-js module passes in the version of the OpenTok.js SDK it should use. Also my understanding is that OpenTok.js update enforces use of the Unified Plan on newer browsers, and that for legacy browsers, OpenTok.js continues to use Plan B. (See the "fixed issues" section of [the OpenTok.js release notes](https://tokbox.com/developer/sdks/js/release-notes.html#fixedIssues), and see the issues fixed in OpenTok.js 2.20.1.)

Guillaume, what version of OpenTok.js are you passing into the network test? Which browser (and version) are you using? And what error are you seeing?

**Comment by guillaumepotier** [comment]
Hi @jeffswartz , thanks for your answer!

We're using the latest version of this lib [on this test page](https://www.wisembly.com/connectivity/index.html)
And on latest Chrome, I have a nice error in console about Plan B deprecation. `opentok-network-test-js` is my only `opentok` dependency, so I suspect this is that one that loads opentok.js client.

Let me know if that helps

Best

**Comment by jeffswartz** [comment]
I see that your test page loads version 2.18.0 OpenTok.js. The developer console error message about Plan B was fixed in version 2.18.5 (see https://tokbox.com/developer/sdks/js/release-notes.html#fixedIssues). Also, version 2.18.x is no longer supported. I recommend loading the OpenTok.js library from https://static.opentok.com/v2/js/opentok.js (or using the latest version of 2.x on npmjs.com).

**Comment by guillaumepotier** [comment]
You're right, my bad. I misread the `package.json` and indeed I was using an outdated version of `@opentok/client`.
